apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "graph-explorer.fullname" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "graph-explorer.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      {{- include "graph-explorer.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "graph-explorer.selectorLabels" . | nindent 8 }}
    spec:
      serviceAccountName: {{ .Values.serviceAccount.name }}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      containers:
        - name: graph-explorer
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          command:
            - /bin/sh
            - -lc
          args:
            - >-
              ./process-environment.sh &&
              cd /graph-explorer/packages/graph-explorer-proxy-server &&
              exec env NODE_ENV=production node dist/node-server.js
          ports:
            - name: http
              containerPort: 80
              protocol: TCP
          env:
            {{- range $key, $value := .Values.env }}
            - name: {{ $key }}
              value: {{ $value | quote }}
            {{- end }}
            {{- if .Values.externalSecrets.enabled }}
            - name: GRAPH_CONNECTION_URL
              valueFrom:
                secretKeyRef:
                  name: neptune-connection-graph-explorer
                  key: GRAPH_CONNECTION_URL
            {{- end }}
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
