{{- if .Values.externalSecrets.enabled }}
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: neptune-connection-graph-explorer
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "graph-explorer.labels" . | nindent 4 }}
spec:
  refreshInterval: {{ .Values.externalSecrets.refreshInterval }}
  secretStoreRef:
    name: {{ .Values.externalSecrets.secretStoreName }}
    kind: {{ .Values.externalSecrets.secretStoreKind }}
  target:
    name: neptune-connection-graph-explorer
    creationPolicy: Owner
    template:
      engineVersion: v2
      data:
        GRAPH_CONNECTION_URL: "https://{{ "{{ .host }}" }}:{{ "{{ .port }}" }}"
  data:
    - secretKey: host
      remoteRef:
        key: {{ .Values.neptune.secretKey }}
        property: host
    - secretKey: port
      remoteRef:
        key: {{ .Values.neptune.secretKey }}
        property: port
{{- end }}
