"""add media table and profile_image_id

Revision ID: 6a42baca319e
Revises: 002
Create Date: 2025-11-29 05:04:20.312046

"""

from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision = "6a42baca319e"
down_revision = "002"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("legacies", sa.Column("profile_image_id", sa.UUID(), nullable=True))
    op.drop_index(op.f("idx_legacies_created_at"), table_name="legacies")
    op.drop_index(op.f("idx_legacies_created_by"), table_name="legacies")
    op.drop_index(op.f("idx_legacies_name"), table_name="legacies")
    op.drop_index(
        op.f("idx_legacies_name_trgm"),
        table_name="legacies",
        postgresql_ops={"name": "gin_trgm_ops"},
        postgresql_using="gin",
    )
    op.create_index(
        op.f("ix_legacies_created_at"), "legacies", ["created_at"], unique=False
    )
    op.create_index(
        op.f("ix_legacies_created_by"), "legacies", ["created_by"], unique=False
    )
    op.create_index(op.f("ix_legacies_name"), "legacies", ["name"], unique=False)
    op.create_index(
        op.f("ix_legacies_profile_image_id"),
        "legacies",
        ["profile_image_id"],
        unique=False,
    )
    op.create_foreign_key(
        None, "legacies", "media", ["profile_image_id"], ["id"], ondelete="SET NULL"
    )
    op.drop_index(op.f("idx_legacy_members_legacy"), table_name="legacy_members")
    op.drop_index(op.f("idx_legacy_members_role"), table_name="legacy_members")
    op.drop_index(op.f("idx_legacy_members_user"), table_name="legacy_members")
    op.create_index(
        op.f("ix_legacy_members_role"), "legacy_members", ["role"], unique=False
    )
    op.create_unique_constraint(
        "uq_legacy_member", "legacy_members", ["legacy_id", "user_id"]
    )
    op.add_column(
        "media", sa.Column("storage_path", sa.String(length=500), nullable=False)
    )
    op.add_column("media", sa.Column("uploaded_by", sa.UUID(), nullable=False))
    op.alter_column("media", "legacy_id", existing_type=sa.UUID(), nullable=False)
    op.drop_index(op.f("idx_media_created_at"), table_name="media")
    op.drop_index(
        op.f("idx_media_legacy"),
        table_name="media",
        postgresql_where="(legacy_id IS NOT NULL)",
    )
    op.drop_index(op.f("idx_media_user"), table_name="media")
    op.drop_constraint(op.f("uq_media_s3_location"), "media", type_="unique")
    op.create_index(op.f("ix_media_created_at"), "media", ["created_at"], unique=False)
    op.create_index(op.f("ix_media_legacy_id"), "media", ["legacy_id"], unique=False)
    op.create_index(
        op.f("ix_media_uploaded_by"), "media", ["uploaded_by"], unique=False
    )
    op.drop_constraint(op.f("media_legacy_id_fkey"), "media", type_="foreignkey")
    op.drop_constraint(op.f("media_user_id_fkey"), "media", type_="foreignkey")
    op.create_foreign_key(
        None, "media", "legacies", ["legacy_id"], ["id"], ondelete="CASCADE"
    )
    op.create_foreign_key(
        None, "media", "users", ["uploaded_by"], ["id"], ondelete="CASCADE"
    )
    op.drop_column("media", "s3_bucket")
    op.drop_column("media", "user_id")
    op.drop_column("media", "s3_key")
    op.drop_index(op.f("idx_users_email"), table_name="users")
    op.drop_index(op.f("idx_users_google_id"), table_name="users")
    op.drop_constraint(op.f("users_email_key"), "users", type_="unique")
    op.drop_constraint(op.f("users_google_id_key"), "users", type_="unique")
    op.create_index(op.f("ix_users_email"), "users", ["email"], unique=True)
    op.create_index(op.f("ix_users_google_id"), "users", ["google_id"], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_users_google_id"), table_name="users")
    op.drop_index(op.f("ix_users_email"), table_name="users")
    op.create_unique_constraint(
        op.f("users_google_id_key"),
        "users",
        ["google_id"],
        postgresql_nulls_not_distinct=False,
    )
    op.create_unique_constraint(
        op.f("users_email_key"), "users", ["email"], postgresql_nulls_not_distinct=False
    )
    op.create_index(op.f("idx_users_google_id"), "users", ["google_id"], unique=False)
    op.create_index(op.f("idx_users_email"), "users", ["email"], unique=False)
    op.add_column(
        "media",
        sa.Column(
            "s3_key", sa.VARCHAR(length=500), autoincrement=False, nullable=False
        ),
    )
    op.add_column(
        "media", sa.Column("user_id", sa.UUID(), autoincrement=False, nullable=False)
    )
    op.add_column(
        "media",
        sa.Column(
            "s3_bucket", sa.VARCHAR(length=100), autoincrement=False, nullable=False
        ),
    )
    op.drop_constraint(None, "media", type_="foreignkey")
    op.drop_constraint(None, "media", type_="foreignkey")
    op.create_foreign_key(
        op.f("media_user_id_fkey"),
        "media",
        "users",
        ["user_id"],
        ["id"],
        ondelete="CASCADE",
    )
    op.create_foreign_key(
        op.f("media_legacy_id_fkey"),
        "media",
        "legacies",
        ["legacy_id"],
        ["id"],
        ondelete="SET NULL",
    )
    op.drop_index(op.f("ix_media_uploaded_by"), table_name="media")
    op.drop_index(op.f("ix_media_legacy_id"), table_name="media")
    op.drop_index(op.f("ix_media_created_at"), table_name="media")
    op.create_unique_constraint(
        op.f("uq_media_s3_location"),
        "media",
        ["s3_bucket", "s3_key"],
        postgresql_nulls_not_distinct=False,
    )
    op.create_index(op.f("idx_media_user"), "media", ["user_id"], unique=False)
    op.create_index(
        op.f("idx_media_legacy"),
        "media",
        ["legacy_id"],
        unique=False,
        postgresql_where="(legacy_id IS NOT NULL)",
    )
    op.create_index(op.f("idx_media_created_at"), "media", ["created_at"], unique=False)
    op.alter_column("media", "legacy_id", existing_type=sa.UUID(), nullable=True)
    op.drop_column("media", "uploaded_by")
    op.drop_column("media", "storage_path")
    op.drop_constraint("uq_legacy_member", "legacy_members", type_="unique")
    op.drop_index(op.f("ix_legacy_members_role"), table_name="legacy_members")
    op.create_index(
        op.f("idx_legacy_members_user"), "legacy_members", ["user_id"], unique=False
    )
    op.create_index(
        op.f("idx_legacy_members_role"), "legacy_members", ["role"], unique=False
    )
    op.create_index(
        op.f("idx_legacy_members_legacy"), "legacy_members", ["legacy_id"], unique=False
    )
    op.drop_constraint(None, "legacies", type_="foreignkey")
    op.drop_index(op.f("ix_legacies_profile_image_id"), table_name="legacies")
    op.drop_index(op.f("ix_legacies_name"), table_name="legacies")
    op.drop_index(op.f("ix_legacies_created_by"), table_name="legacies")
    op.drop_index(op.f("ix_legacies_created_at"), table_name="legacies")
    op.create_index(
        op.f("idx_legacies_name_trgm"),
        "legacies",
        ["name"],
        unique=False,
        postgresql_ops={"name": "gin_trgm_ops"},
        postgresql_using="gin",
    )
    op.create_index(op.f("idx_legacies_name"), "legacies", ["name"], unique=False)
    op.create_index(
        op.f("idx_legacies_created_by"), "legacies", ["created_by"], unique=False
    )
    op.create_index(
        op.f("idx_legacies_created_at"), "legacies", ["created_at"], unique=False
    )
    op.drop_column("legacies", "profile_image_id")
    # ### end Alembic commands ###
