"""add_blocked_to_ai_messages

Revision ID: bdc85d7aa67a
Revises: 79d887dbb207
Create Date: 2025-12-09 17:38:11.037096

"""

from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision = "bdc85d7aa67a"
down_revision = "79d887dbb207"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # Add blocked column to ai_messages
    op.add_column(
        "ai_messages",
        sa.Column("blocked", sa.Boolean(), server_default="false", nullable=False),
    )

    # Add partial index for efficient context message queries (excludes blocked messages)
    op.create_index(
        "idx_ai_messages_context_lookup",
        "ai_messages",
        ["conversation_id", "created_at"],
        postgresql_where=sa.text("blocked = false"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # Drop the partial index first
    op.drop_index("idx_ai_messages_context_lookup", table_name="ai_messages")

    # Drop the blocked column
    op.drop_column("ai_messages", "blocked")
    # ### end Alembic commands ###
