apiVersion: v1
kind: Secret
metadata:
  name: {{ include "core-api.fullname" . }}-secrets
type: Opaque
stringData:
  DB_URL: {{ .Values.secrets.DB_URL | quote }}
  OIDC_CLIENT_SECRET: {{ .Values.secrets.OIDC_CLIENT_SECRET | quote }}

