{{- if and .Values.web.enabled .Values.web.autoscaling.enabled }}
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: {{ .Values.web.name }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "mosaic-life.labels" . | nindent 4 }}
    {{- include "mosaic-life.web.selectorLabels" . | nindent 4 }}
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: {{ .Values.web.name }}
  minReplicas: {{ .Values.web.autoscaling.minReplicas }}
  maxReplicas: {{ .Values.web.autoscaling.maxReplicas }}
  metrics:
  {{- if .Values.web.autoscaling.targetCPUUtilizationPercentage }}
  - type: Resource
    resource:
      name: cpu
      target:
        type: Utilization
        averageUtilization: {{ .Values.web.autoscaling.targetCPUUtilizationPercentage }}
  {{- end }}
  {{- if .Values.web.autoscaling.targetMemoryUtilizationPercentage }}
  - type: Resource
    resource:
      name: memory
      target:
        type: Utilization
        averageUtilization: {{ .Values.web.autoscaling.targetMemoryUtilizationPercentage }}
  {{- end }}
{{- end }}
