{{- if .Values.web.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.web.name }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "mosaic-life.labels" . | nindent 4 }}
    {{- include "mosaic-life.web.selectorLabels" . | nindent 4 }}
spec:
  type: {{ .Values.web.service.type }}
  ports:
  - port: {{ .Values.web.service.port }}
    targetPort: {{ .Values.web.service.targetPort }}
    protocol: TCP
    name: http
  selector:
    {{- include "mosaic-life.web.selectorLabels" . | nindent 4 }}
{{- end }}
