apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: mosaic-life-prod
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
  annotations:
    notifications.argoproj.io/subscribe.on-deployed.slack: mosaic-deployments
    notifications.argoproj.io/subscribe.on-health-degraded.slack: mosaic-alerts
spec:
  project: mosaic-life

  # Multi-source: Helm chart from app repo + values from gitops repo
  sources:
    # Source 1: Helm chart from application repository
    - repoURL: https://github.com/mosaic-stories/mosaic-life
      targetRevision: main
      path: infra/helm/mosaic-life
      helm:
        valueFiles:
          - $values/environments/prod/values.yaml
          - $values/base/values.yaml
    
    # Source 2: Values from GitOps repository  
    - repoURL: https://github.com/mosaic-stories/gitops.git
      targetRevision: main
      ref: values

  destination:
    server: https://kubernetes.default.svc
    namespace: mosaic-prod

  syncPolicy:
    automated:
      prune: true
      selfHeal: true
      allowEmpty: false
    syncOptions:
      - CreateNamespace=true
      - PrunePropagationPolicy=foreground
      - PruneLast=true
    retry:
      limit: 5
      backoff:
        duration: 5s
        factor: 2
        maxDuration: 3m

  # Health assessment
  ignoreDifferences:
    - group: apps
      kind: Deployment
      jsonPointers:
        - /spec/replicas  # Ignore HPA-managed replicas

  # Resource tracking
  revisionHistoryLimit: 10
